# Generated by Django 2.0.6 on 2018-07-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parliamentrecord',
            options={'ordering': ['sitting_date', 'title']},
        ),
    ]
