# Generated by Django 2.0.6 on 2018-07-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20180701_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sittingdate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
